### ISSUE TITLE
How does catch functions as forward control quantity?

### ISSUE THREAD

**Issue by mingsun** [flr/FLasher#61]
I am trying to figure out how do you use "catch" as a forward control quantity.
Specifically, how do you allocate catch into different age groups? I tried to look into the code but found nothing.

**Comment by drfinlayscott** [comment]
Hi,
The catch target in the forward control is total catches over all age
classes. The distribution of catches across age classes is given by the
selectivity at age which will already have been set up as a future
assumption in the FLR objects (which can be changed to reflect different
assumptions).

Hope this helps

Finlay

**Comment by mingsun** [comment]
Hi,
Thanks this is interesting.

But I am thinking of an extreme case: is it possible that the distributed
catch for an age-class is higher than then actual biomass?  How will you
avoid this happen?

(say the biomass of age 4 fish is 50 tons while 60 tons of catch is
assigned to age 4 according to selectivity)

**Comment by drfinlayscott** [comment]
Hi,
You cannot catch more than the available biomass. If you try to catch more
than is possible, the solver inside FLasher will (probably) just max out at
some maximum level of fishing effort. The result will be very high fishing
effort and F, almost no biomass and your catch target will not have been
met. Either that or FLasher will crash :). I'm not sure why you would want
to do this...

Kind regards

Finlay
