### ISSUE TITLE
fwd only applies M and not F

### ISSUE THREAD

**Issue by hgerritsen** [flr/FLasher#62]
I have had some issues with the fwd() function. In some cases it works fine (e.g. when using the ple4 dataset) but with my own data, the function does not seem to calculate the stock.n correctly. For some reason it seems to calculate n1 = n0 * exp(-(M+F*1e-6)) instead of n1 = n0 * exp(-(M+F)), so it divides F by a million for some reason.
When i use old FLR packages and the project() function i do not have this issue with the same datset.
The attached zip file contains a stock object and some code to illustrate the point

[forecastWhg.zip](https://github.com/flr/FLasher/files/3738799/forecastWhg.zip)

**Comment by iagomosqueira** [comment]
Not sure what package are you actually loading. Flasher is commented out in your script. And the pasted output says

# R version 3.0.2 (2013-09-25)
# Platform: x86_64-w64-mingw32/x64 (64-bit)

This is really very old. Can you replicate this problem using R 3.6 and the packages available in the FLR repository?

FLasher is the new version of FLash, which requires at least FLCore 2.6.5 and R 3.5.

Please note project() and projectControl() do not exist anymore. You need to use fwd() and fwdControl() to run a forecast with FLash, as in

http://www.flr-project.org/doc/Short_Term_Forecasting_for_advice_using_FLash.html

FLasher is almost 100% equivalent, but there are small differences in syntax, see for example

http://www.flr-project.org/doc/Forecasting_on_the_Medium_Term_for_advice_using_FLasher.html

**Comment by hgerritsen** [comment]
Oh i might have sent the wrkng script, sorry  will check and send the correct one later. I.m out of the office now.
Sorry.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by hgerritsen** [comment]
[forecastWhg.zip](https://github.com/flr/FLasher/files/3739884/forecastWhg.zip)

here is the correct script

**Comment by iagomosqueira** [comment]
Thanks for reporting. The issue had to do with the calculation of survivors for stocks with an age 0. It had been already fixed but was not yet in a released package. Will be on next release.
