### ISSUE TITLE
Error when activating verbose on operating_model.cpp

### ISSUE THREAD

**Issue by romarcha** [flr/FLasher#66]
If verbose is activated on operating_model.cpp the following lines throw an error.

`if(verbose){Rprintf("Age 0 survivors surv 1: %f surv 2: %f\n", Value(surv(1,1,1,1,1,1)), Value(surv(1,1,2,1,1,1)));}`

This is line 752 of operating_model.cpp

Best,

Roman

**Comment by iagomosqueira** [comment]
I think they are various issues with some of the commands launched by verbose=true. We will have to take a look and have a solid setup for checking results.

**Comment by iagomosqueira** [comment]
Not really fixed, but waiting for a review of verbose and debugging options in FLasher
